### ISSUE TITLE
class_labels_indices.csv is missing in psla/egs/fsd50k/class_labels_indices.csv

### ISSUE THREAD

**Issue by maxime-leiber** [YuanGongND/psla#1]
File 'class_labels_indices.csv' is missing from the following path 'egs/fsd50k/class_labels_indices.csv'.

To reproduce:
python psla/egs/fsd50k/prep_fsd.py >> No such file or directory: './class_labels_indices.csv'
python psla/src/label_enhancement/fix_type1.py >>  No such file or directory: '../../egs/fsd50k/class_labels_indices.csv'

**Comment by YuanGongND** [comment]
Thanks. Just added the missing file. 

-Yuan
