### ISSUE TITLE
file `ontology.json` not found

### ISSUE THREAD

**Issue by cld4h** [YuanGongND/psla#2]
https://github.com/YuanGongND/psla/blob/16be23969a66802a71f10a331cdec8e512a14a29/src/label_enhancement/fix_type2.py#L18

**Comment by YuanGongND** [comment]
Hi there,

I think it is at [here](https://github.com/YuanGongND/psla/blob/main/src/utilities/ontology.json), which is from [this repo](https://github.com/audioset/ontology).

-Yuan

**Comment by cld4h** [comment]
Thanks!

**Comment by tiansiyuan** [comment]
https://github.com/YuanGongND/psla/pull/13

This PR can fix this problem.

Regards
